site_name: Mòdul 0483 - Sistemes informàtics
site_description: Publicació progressiva des d'un sol repositori
site_url: https://jpardo20.github.io/digi-0483-sistemes-informatics/

nav:
  - Inici: index.md
  - Continguts: continguts.md
  - Activitat 1: 0483-activitat-001-docker-web.md


theme:
  name: material
  language: ca
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - content.code.copy

extra_css:
  - assets/styles.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
